### ISSUE TITLE
Починить лабелер

### ISSUE THREAD

**Issue by lex111** [doka-guide/content#2202]
Пример - https://github.com/doka-guide/content/runs/4026988052?check_suite_focus=true (PR - https://github.com/doka-guide/content/pull/2198)

```
(node:1619) UnhandledPromiseRejectionWarning: HttpError: Resource not accessible by integration
    at /home/runner/work/content/content/node_modules/@octokit/request/dist-node/index.js:86:21
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async setupLabels (/home/runner/work/content/content/.github/scripts/labeler.js:105:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1619) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1619) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by lex111** [comment]
Что-то снова не то https://github.com/doka-guide/content/runs/4144969390?check_suite_focus=true

**Comment by igsekor** [comment]
> Что-то снова не то https://github.com/doka-guide/content/runs/4144969390?check_suite_focus=true

Тине должно быть. Я поправил скрипт. Остальные изменения в следующем пиаре. Там, где превью.

**Comment by lex111** [comment]
Ок, надеюсь тогда всё будет исправлено, иначе сейчас я получаю два письма по разным воркфлоу, причем одно дублируется ещё

![image](https://user-images.githubusercontent.com/4408379/140983676-e7f81fdb-4276-4f80-ae1c-3db59dff5328.png)
