### ISSUE TITLE
Не получается запустить проект локально

### ISSUE THREAD

**Issue by reznikovAndrey** [doka-guide/content#4618]
Пробую на MacBook Air M2.

Действовал по [гайду для локального запуска](https://github.com/doka-guide/content/blob/main/docs/preview.md).

После команды
```sh
./start.sh
```

получил следующую ошибку `no matching manifest for linux/arm64/v8 in the manifest list entries`

Немного погуглив, попробовал слегка изменить скрипт в `start.sh`, добавив `--platform linux/x86_64/v8`, по итогу получилось вот так:

```sh
docker pull dokaguide/platform --platform linux/x86_64/v8 && docker run --rm -p "$WS_IP":"$WS_PORT":8080/tcp -v "$(pwd)"/:/platform/content dokaguide/platform
```

получил следующую ошибку
```
[11ty] Problem writing Eleventy templates: (more in DEBUG output)
[11ty] This endpoint requires you to be authenticated. (via HttpError)
[11ty] 
[11ty] Original error stack trace: HttpError: This endpoint requires you to be authenticated.
[11ty]     at /platform/node_modules/@octokit/request/dist-node/index.js:86:21
[11ty]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[11ty]     at async Promise.all (index 0)
[11ty]     at async getAuthorsContribution (/platform/src/libs/github-contribution-service/github-contribution-service.js:163:39)
[11ty] Copied 1614 files / Wrote 0 files in 58.09 seconds (v1.0.2)
```

**Comment by TatianaFokina** [comment]
@igsekor, подскажешь в чём проблема?

**Comment by TatianaFokina** [comment]
@reznikovAndrey, как вариант, можешь попробовать собрать проект без Докера. В [этой инструкции](https://github.com/doka-guide/platform/blob/main/docs/how-to-run.md) описано, как это сделать.

**Comment by reznikovAndrey** [comment]
> @reznikovAndrey, как вариант, можешь попробовать собрать проект без Докера. В [этой инструкции](https://github.com/doka-guide/platform/blob/main/docs/how-to-run.md) описано, как это сделать.

Спасибо, по этой инструкции удалось запустить локально)

**Comment by solarrust** [comment]
Тогда задачку пока закрываю, раз запустить удалось.
